### ISSUE TITLE
Problem onRestoreInstance

### ISSUE THREAD

**Issue by cazador4** [fython/MaterialStepperView#16]
Caused by: java.lang.ClassCastException: android.view.View$BaseSavedState cannot be cast to moe.feng.common.stepperview.VerticalStepperItemView$ItemViewState
                                                                              at moe.feng.common.stepperview.VerticalStepperItemView.onRestoreInstanceState(VerticalStepperItemView.java:778)
                                                                              at android.view.View.dispatchRestoreInstanceState(View.java:17706)
                                                                              at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3745)
                                                                              at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
                                                                              at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
                                                                              at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
                                                                              at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
                                                                              at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
                                                                              at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
                                                                              at android.view.View.restoreHierarchyState(View.java:17684)
                                                                              at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2131)
                                                                              at android.app.Activity.onRestoreInstanceState(Activity.java:1102)
                                                                              at

**Comment by GenaritoBike** [comment]
Hi,

I have the same problem

Milos

**Comment by fython** [comment]
Sorry for finishing fix so late. Now it works well in commit 958430e8af47bbab47b1b1040c9f739f67e41ad1 . I will release new version of library soon.

**Comment by cazador4** [comment]
Thanks man!
