### ISSUE TITLE
View InflateException

### ISSUE THREAD

**Issue by LvWind** [fython/MaterialStepperView#9]
here's the log
> Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{<package>/<package>.GuideActivity}: android.view.InflateException: Binary XML file line #16: Error inflating class moe.feng.common.stepperview.VerticalStepperItemView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
       at android.app.ActivityThread.access$900(ActivityThread.java:170)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5635)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by android.view.InflateException: Binary XML file line #16: Error inflating class moe.feng.common.stepperview.VerticalStepperItemView
       at android.view.LayoutInflater.createView(LayoutInflater.java:626)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
       at <package>.GuideActivity.onCreate(GuideActivity.kt:24)
       at android.app.Activity.performCreate(Activity.java:5585)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
       at android.app.ActivityThread.access$900(ActivityThread.java:170)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5635)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:600)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
       at <package>.GuideActivity.onCreate(GuideActivity.kt:24)
       at android.app.Activity.performCreate(Activity.java:5585)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
       at android.app.ActivityThread.access$900(ActivityThread.java:170)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5635)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)
**Caused by java.lang.NoSuchMethodError: android.animation.ObjectAnimator.ofArgb
       at moe.feng.common.stepperview.VerticalStepperItemView.setState(VerticalStepperItemView.java:246)
       at moe.feng.common.stepperview.VerticalStepperItemView.<init>(VerticalStepperItemView.java:110)
       at moe.feng.common.stepperview.VerticalStepperItemView.<init>(VerticalStepperItemView.java:74)**
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:600)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
       at <package>.GuideActivity.onCreate(GuideActivity.kt:24)
       at android.app.Activity.performCreate(Activity.java:5585)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
       at android.app.ActivityThread.access$900(ActivityThread.java:170)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5635)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by LvWind** [comment]
ObjectAnimator.ofArgb was added in API level 21.
so, #2 is not completed

**Comment by LvWind** [comment]
Maybe a solution
[http://blog.csdn.net/iispring/article/details/50322625](http://blog.csdn.net/iispring/article/details/50322625)

**Comment by fython** [comment]
@LvWind Thanks for suggestion. I forgot that unsupported method under SDK < 21 is `ObjectAnimator.ofArgb`.

**Comment by LvWind** [comment]
I tested with this solution and opened a new PR

**Comment by fython** [comment]
Commited changed f21bd30c17c87bdb8703aa534b21e38aa36e953c . Next release/tag will fix it.
